<?php

declare(strict_types=1);

namespace Nowo\TimeTrackBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Configuration tree for TimeTrackBundle.
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_time_track';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $root        = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('user_class')
                    ->info('FQCN of the application user entity (must implement UserInterface and expose getId()).')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->example('App\\Entity\\User')
                ->end()
                ->scalarNode('table_prefix')
                    ->info('Prefix for time track tables (entries, active_timers, client_tokens).')
                    ->defaultValue('time_track_')
                    ->cannotBeEmpty()
                ->end()
                ->scalarNode('task_provider')
                    ->info('Service id implementing TaskProviderInterface. Defaults to StubTaskProvider for demos.')
                    ->defaultValue(\Nowo\TimeTrackBundle\Bridge\StubTaskProvider::class)
                ->end()
                ->scalarNode('team_context_provider')
                    ->info('Service id implementing TeamContextProviderInterface.')
                    ->defaultValue(\Nowo\TimeTrackBundle\Bridge\NullTeamContextProvider::class)
                ->end()
                ->scalarNode('route_prefix')
                    ->defaultValue('')
                ->end()
                ->arrayNode('database')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('entity_manager')
                            ->defaultValue('default')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('admin_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_ADMIN'])
                        ->end()
                        ->arrayNode('access_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_USER'])
                        ->end()
                        ->booleanNode('manager_can_view_entries')
                            ->defaultTrue()
                        ->end()
                        ->booleanNode('manager_can_edit_entries')
                            ->defaultTrue()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('routes')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('index')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('path')->defaultValue('/tools/time-track')->end()
                                ->scalarNode('name')->defaultValue('nowo_time_track_index')->end()
                            ->end()
                        ->end()
                        ->arrayNode('reports')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('path')->defaultValue('/tools/time-track/reports')->end()
                                ->scalarNode('name')->defaultValue('nowo_time_track_reports')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('templates')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('layout')
                            ->defaultValue('@NowoTimeTrackBundle/layout.html.twig')
                        ->end()
                        ->scalarNode('index')
                            ->defaultValue('@NowoTimeTrackBundle/time_track/index.html.twig')
                        ->end()
                        ->scalarNode('reports')
                            ->defaultValue('@NowoTimeTrackBundle/time_track/reports.html.twig')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('clients')
                    ->info('Browser extension and Tauri desktop agent API (Bearer token auth).')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->integerNode('token_ttl')
                            ->info('Bearer token lifetime in seconds.')
                            ->defaultValue(86_400)
                            ->min(60)
                        ->end()
                        ->integerNode('idle_threshold_seconds')
                            ->info('Desktop idle detection threshold in seconds.')
                            ->defaultValue(300)
                            ->min(60)
                        ->end()
                        ->scalarNode('authenticator')
                            ->info('Service id implementing ClientAuthenticatorInterface.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('user_provider')
                            ->info('Symfony user provider for default password authenticator.')
                            ->defaultNull()
                        ->end()
                        ->arrayNode('cors_allowed_origins')
                            ->info('Extra allowed CORS origins (chrome-extension:// and tauri:// are always allowed).')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('login_rate_limit')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                ->end()
                                ->scalarNode('cache_pool')
                                    ->defaultValue('cache.app')
                                ->end()
                                ->integerNode('max_attempts')
                                    ->defaultValue(10)
                                    ->min(1)
                                ->end()
                                ->integerNode('interval_seconds')
                                    ->defaultValue(900)
                                    ->min(60)
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('routes')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('login')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/login')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_login')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('logout')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/logout')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_logout')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('me')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/me')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_me')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('tasks')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/tasks')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_tasks')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('timer')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/timer')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_timer')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('timer_start')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/timer/start')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_timer_start')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('timer_stop')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/timer/stop')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_timer_stop')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('heartbeat')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/heartbeat')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_heartbeat')->end()
                                    ->end()
                                ->end()
                                ->arrayNode('entries')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('path')->defaultValue('/api/time-track/entries')->end()
                                        ->scalarNode('name')->defaultValue('nowo_time_track_api_entries')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
